Aspire
AzureCosmosDB/cosmosdb-nosql-copilot pull request #45
Opened 2024-10-25 15:07 UTC by markjbrown

2024-10-25 15:23 UTC, jcocchi approved these changes

2024-10-25 22:19 UTC, jcocchi requested changes
We need to change the serialization to use `System.Text.Json` in the SemanticKernelService. 
Can't leave comments on the lines directly because they weren't edited in this PR, but line 253 should read:
`string productsString = JsonSerializer.Serialize(resultRecords);`

Line 280: 
`List<Product> products = JsonSerializer.Deserialize<List<Product>>(json)!;`

And add using at the top
`using System.Text.Json;`

2024-10-26 10:22 UTC, markjbrown commented on src/cosmos-copilot.WebApp/Program.cs
> +        settings.AccountEndpoint = new Uri(cosmosEndpoint!);
removed that second one.

2024-10-26 10:28 UTC, markjbrown commented
Fixed issues.

2024-10-26 10:28 UTC, merged